import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { EditorOutputMode, EditorPreset } from '../../types/index.js';

const BUILTIN_EDITOR_PRESETS: EditorPreset[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    filePath: '.claude/skills',
    type: 'directory',
    outputMode: 'directory',
    defaultEnabled: true,
    isSkillType: true,
    source: 'builtin',
  },
  {
    id: 'hermes',
    name: 'Hermes',
    filePath: '.hermes/skills',
    type: 'directory',
    outputMode: 'directory',
    defaultEnabled: true,
    isSkillType: true,
    source: 'builtin',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    filePath: '.cursorrules',
    type: 'file',
    outputMode: 'marker-file',
    defaultEnabled: true,
    isSkillType: false,
    headerTemplate: '# Cursor Rules\n\n> Generated by open-skills for {count} skill(s)\n\n',
    source: 'builtin',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    filePath: '.windsurfrules',
    type: 'file',
    outputMode: 'marker-file',
    defaultEnabled: true,
    isSkillType: false,
    headerTemplate: '# Windsurf Rules\n\n> Generated by open-skills for {count} skill(s)\n\n',
    source: 'builtin',
  },
  {
    id: 'cline',
    name: 'Cline',
    filePath: '.clinerules',
    type: 'file',
    outputMode: 'marker-file',
    defaultEnabled: true,
    isSkillType: false,
    headerTemplate: '# Cline Rules\n\n> Generated by open-skills for {count} skill(s)\n\n',
    source: 'builtin',
  },
  {
    id: 'cursor-skills',
    name: 'Cursor Skills',
    filePath: '.cursor/skills',
    type: 'directory',
    outputMode: 'directory',
    defaultEnabled: true,
    isSkillType: true,
    source: 'builtin',
  },
  {
    id: 'roo-cline',
    name: 'Roo-Cline',
    filePath: '.roorules',
    type: 'file',
    outputMode: 'marker-file',
    defaultEnabled: true,
    isSkillType: false,
    headerTemplate: '# Roo-Cline Rules\n\n> Generated by open-skills for {count} skill(s)\n\n',
    source: 'builtin',
  },
  {
    id: 'antigravity',
    name: 'Antigravity',
    filePath: '.agents/skills',
    type: 'directory',
    outputMode: 'directory',
    defaultEnabled: true,
    isSkillType: true,
    source: 'builtin',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    filePath: '.github/skills',
    type: 'directory',
    outputMode: 'directory',
    defaultEnabled: false,
    isSkillType: true,
    source: 'builtin',
  },
];

interface RawEditorPreset {
  id?: unknown;
  name?: unknown;
  filePath?: unknown;
  type?: unknown;
  outputMode?: unknown;
  defaultEnabled?: unknown;
  isSkillType?: unknown;
  headerTemplate?: unknown;
}

interface PluginConfigFile {
  agents?: unknown;
  editors?: unknown;
}

const PLUGIN_PATHS = [
  path.join(process.cwd(), '.open-skills', 'agents.json'),
  path.join(process.cwd(), '.open-skills', 'plugins.json'),
  path.join(os.homedir(), '.open-skills', 'agents.json'),
];

function toNonEmptyString(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function toOutputMode(value: unknown): EditorOutputMode {
  return value === 'plain-file' || value === 'directory' || value === 'marker-file'
    ? value
    : 'marker-file';
}

function normalizePreset(raw: RawEditorPreset): EditorPreset | null {
  const id = toNonEmptyString(raw.id);
  const name = toNonEmptyString(raw.name);
  const filePath = toNonEmptyString(raw.filePath);
  const type = raw.type === 'directory' ? 'directory' : 'file';
  const outputMode = raw.outputMode ? toOutputMode(raw.outputMode) : (type === 'directory' ? 'directory' : 'marker-file');

  if (!id || !name || !filePath) return null;

  return {
    id,
    name,
    filePath,
    type,
    outputMode,
    defaultEnabled: !!raw.defaultEnabled,
    isSkillType: raw.isSkillType === undefined ? true : !!raw.isSkillType,
    headerTemplate: toNonEmptyString(raw.headerTemplate) || undefined,
    source: 'plugin',
  };
}

function readPluginPresetsFromFile(filePath: string): EditorPreset[] {
  if (!fs.existsSync(filePath)) return [];

  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const parsed = JSON.parse(content) as PluginConfigFile | unknown;
    const list = Array.isArray(parsed)
      ? parsed
      : parsed && typeof parsed === 'object'
        ? (Array.isArray((parsed as PluginConfigFile).agents)
          ? (parsed as PluginConfigFile).agents
          : Array.isArray((parsed as PluginConfigFile).editors)
            ? (parsed as PluginConfigFile).editors
            : [])
        : [];

    if (!Array.isArray(list)) return [];
    return list
      .map((item) => normalizePreset(item as RawEditorPreset))
      .filter((item): item is EditorPreset => item !== null);
  } catch {
    return [];
  }
}

function loadEditorPresets(): EditorPreset[] {
  const presetMap = new Map<string, EditorPreset>();

  for (const preset of BUILTIN_EDITOR_PRESETS) {
    presetMap.set(preset.id, preset);
  }

  for (const pluginPath of PLUGIN_PATHS) {
    for (const pluginPreset of readPluginPresetsFromFile(pluginPath)) {
      const basePreset = presetMap.get(pluginPreset.id);
      presetMap.set(pluginPreset.id, {
        ...basePreset,
        ...pluginPreset,
      });
    }
  }

  return Array.from(presetMap.values());
}

export const editorPresets = Object.freeze(loadEditorPresets());
