import * as path from 'node:path';
import type { InstallScope, SkillMeta, InstallResult } from '../../types/index.js';
import { ensureDir, writeFile } from '../../core/fs-utils.js';
import { BaseAdapter } from './base-adapter.js';

export class PlainFileAdapter extends BaseAdapter {
  generateHeaderContent(): string {
    return `# Skills Snapshot\n\n> Generated by open-skills\n\n`;
  }

  transformSkillContent(content: string): string {
    return content;
  }

  shouldGenerateIndex(): boolean {
    return false;
  }

  shouldCopySkillDirectory(): boolean {
    return false;
  }

  async generateOutput(
    scope: InstallScope,
    skills: SkillMeta[],
    skillContents: Map<string, string>
  ): Promise<InstallResult[]> {
    const targetPath = this.getTargetPath(scope);
    const body = skills
      .map((skill) => {
        const content = skillContents.get(skill.name) || '';
        return `## ${skill.display_name}\n\n${content}`;
      })
      .join('\n\n---\n\n');

    await ensureDir(path.dirname(targetPath));
    const header = this.generateHeaderContent();
    await writeFile(targetPath, `${header}${body}`.trimEnd(), 'utf-8');

    return skills.map((skill) => ({
      skill,
      success: true,
      message: `Synced to ${targetPath}`,
      targetPath,
    }));
  }
}
